import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mticker


def paymentType_X_totalAmount(data):

    # ---- keep valid payment types ----
    data = data[data['payment_type'].isin([0,1,2,3,4,5,6])]

    # ---- mapping ----
    mapping = {
        0: 'Flex Fare',
        1: 'Credit Card',
        2: 'Cash',
        3: 'No Charge',
        4: 'Dispute',
        5: 'Unknown',
        6: 'Voided Trip'
    }

    # ---- aggregate revenue ----
    revenue = (
        data.groupby('payment_type')['total_amount']
        .sum()
        .reset_index()
    )

    revenue['PaymentType'] = revenue['payment_type'].map(mapping)

    # sort biggest first
    revenue = revenue.sort_values(
        by='total_amount',
        ascending=False
    )

    # ---- plotting ----
    plt.style.use('fast')

    fig, axes = plt.subplots(
        2, 4,
        figsize=(16, 8) , sharey=True
    )

    axes = axes.flatten()

    colors = sns.color_palette('Set2', len(revenue))

    for i, (_, row) in enumerate(revenue.iterrows()):

        ax = axes[i]

        ax.bar(
            row['PaymentType'],
            row['total_amount'],
            color=colors[i]
        )

        # value label
        ax.text(
            0,
            row['total_amount'],
            f"${row['total_amount']:,.0f}",
            ha='center',
            va='bottom',
            fontsize=10,
            fontweight='bold'
        )

        #ax.set_title(row['PaymentType'])

        # remove clutter
        ax.set_xlabel('')
        ax.set_ylabel('')

        ax.yaxis.set_major_formatter(
            mticker.StrMethodFormatter('${x:,.0f}')
        )

        sns.despine(ax=ax)

    # remove empty subplot
    fig.delaxes(axes[-1])
    fig.delaxes(axes[-2])

    plt.suptitle(
        'Revenue Generated by Payment Type',
        fontsize=16,
        fontweight='bold'
    )

    plt.tight_layout()

    plt.savefig(
        'paymentType_X_totalAmount.png',
        dpi=150,
        bbox_inches='tight'
    )

    plt.show()